const userData = {
  title: "forecho - Developer, Writer and Creator",
  description: `I've been developing websites for 9 years straight. Get in touch with me to know more.`,
  githubUsername: "forecho",
  name: "forecho",
  designation: "Full-Stack Developer",
  avatarUrl: "https://avatars0.githubusercontent.com/u/1725326?s=460&v=4",
  email: "caizhenghai@gmail.com",
  phone: "",
  address: "China Shenzhen",
  blogUrl: "http://blog.forecho.com/",
  projects: [
    {
      name: "PAHub",
      link: "https://pahubcn.com/",
      description: "专为价格行为交易者打造的在线复盘与学习社区",
      icon: "chart",
      tilt: -1,
    },
    {
      name: "ImgAnt",
      link: "https://imgant.com/",
      description: "支持自定义域名与 API 的图床服务",
      icon: "image",
      tilt: 1,
    },
    {
      name: "4AICode",
      link: "https://4aicode.com/",
      description: "AI 模型中转站，低成本使用 ChatGPT 与图片生成",
      icon: "ai",
      tilt: -1,
    },
    {
      name: "PATimer",
      link: "https://patimer.app/zh/",
      description: "为日内交易员打造的多周期 K 线收盘倒计时工具",
      icon: "timer",
      tilt: 1,
    },
    {
      name: "ExpireMate",
      link: "https://expiremate.app/",
      description: "记录物品保质期，到期前及时提醒，减少浪费",
      icon: "calendar",
      tilt: -1,
    },
    {
      name: "GetYii",
      link: "https://github.com/iiYii/getyii",
      description: "基于 Yii2 开发的开源社区",
      icon: "chat",
      tilt: 1,
    },
    {
      name: "CashWarden",
      link: "https://cashwarden.com/",
      description: "财务管理系统，有开源和商业版本",
      icon: "bank",
      tilt: -1,
    },
    {
      name: "3li3",
      link: "",
      description: "Kindle 电子书以及 iOS APP 降价提醒工具",
      icon: "tag",
      tilt: 1,
    },
    {
      name: "iDevTools",
      link: "",
      description: "开发者在线小工具集合",
      icon: "tool",
      tilt: -1,
    },
  ],

  socialLinks: {
    instagram: "https://instagram.com/forecho",
    twitter: "https://twitter.com/caizhenghai",
    linkedin: "https://linkedin.com/in/forecho",
    github: "https://github.com/forecho",
    telegram: "https://t.me/forecho",
  },
};

export default userData;
